import type { CityPack } from "@/types";

export const raleigh: CityPack = {
  id: "raleigh",
  name: "Raleigh",
  state: "North Carolina",
  center: [-78.6382, 35.7796],
  initialZoom: 11.6,
  initialPitch: 52,
  initialBearing: -14,
  scenarioIds: ["raleigh-hurricane-cascade"],
  status: "playable",
  accent: "#34d399",
  accent2: "#38bdf8",
  hazard: "Inland hurricane flooding",
  scenarioTitle: "Hurricane Cascade",
  difficulty: 3,
  specialMechanic: "Road Isolation",
  question: "What happens when roads disappear?",
  populationTheme: "Creek-side neighborhoods and households without a car",
  hoverEffect: "rain",
  interventionCatalog: [
    { kind: "shelter", snapsTo: "shelterSite" },
    { kind: "busPickup", snapsTo: "busStop" },
    { kind: "protectRoad", snapsTo: "crossing" },
    { kind: "rescueTeam", snapsTo: "fireStation" },
  ],
  interventionNames: [
    "Temporary Shelter",
    "Bus Pickup Point",
    "Protect Critical Road",
    "High-Water Rescue Team",
  ],
  skyline: [
    { t: "box", x: 2, w: 7, h: 8 },
    { t: "box", x: 10, w: 6, h: 12 },
    { t: "dome", x: 18, w: 12, h: 10 },
    { t: "box", x: 32, w: 7, h: 18 },
    { t: "spire", x: 40, w: 9, h: 30, s: 4 },
    { t: "box", x: 50, w: 8, h: 24 },
    { t: "box", x: 59, w: 6, h: 14 },
    { t: "tower", x: 66, w: 8, h: 21 },
    { t: "box", x: 76, w: 7, h: 11 },
    { t: "box", x: 85, w: 6, h: 7 },
    { t: "box", x: 92, w: 6, h: 5 },
  ],
  cameraBookmarks: [
    { id: "downtown", label: "Downtown", center: [-78.6391, 35.7781], zoom: 14.2, pitch: 58, bearing: -20 },
    { id: "crabtree", label: "Crabtree Creek", center: [-78.6505, 35.8285], zoom: 13.4, pitch: 55, bearing: 25 },
    { id: "walnut", label: "Walnut Creek", center: [-78.6142, 35.7468], zoom: 13.4, pitch: 55, bearing: -35 },
    { id: "overview", label: "City overview", center: [-78.6382, 35.8], zoom: 11.3, pitch: 45, bearing: -10 },
  ],
  attribution: [
    { label: "FEMA National Flood Hazard Layer", url: "https://www.fema.gov/flood-maps/national-flood-hazard-layer" },
    { label: "U.S. Census Bureau ACS 5-year", url: "https://www.census.gov/programs-surveys/acs" },
    { label: "© OpenStreetMap contributors", url: "https://www.openstreetmap.org/copyright" },
  ],
  plannedSources: ["NC OneMap", "City of Raleigh Open Data", "USGS stream gauges", "NOAA rainfall"],
};
