import type { CityPack } from "@/types";

export const newYork: CityPack = {
  id: "new-york",
  name: "New York City",
  state: "New York",
  center: [-73.915, 40.832],
  initialZoom: 12.1,
  initialPitch: 60,
  initialBearing: 29,
  scenarioIds: ["nyc-heat-grid"],
  status: "playable",
  accent: "#fb923c",
  accent2: "#f43f5e",
  hazard: "Extreme heat + grid failure",
  scenarioTitle: "Heat Grid",
  difficulty: 4,
  specialMechanic: "Cascading Blackout",
  question: "Who loses protection when the city overheats and the grid weakens?",
  populationTheme: "Older adults without cooling, low tree canopy",
  hoverEffect: "thermal",
  interventionCatalog: [],
  interventionNames: [
    "Cooling Center",
    "Mobile Cooling Bus",
    "Water Station",
    "Backup Generator",
    "Emergency Medical Hub",
    "Shade / Temporary Canopy",
    "Transit Shuttle",
    "Wellness Check Team",
  ],
  skyline: [
    { t: "box", x: 1, w: 5, h: 14 },
    { t: "box", x: 7, w: 4, h: 20 },
    { t: "box", x: 12, w: 5, h: 17 },
    { t: "spire", x: 18, w: 7, h: 32, s: 7 },
    { t: "box", x: 26, w: 4, h: 22 },
    { t: "box", x: 31, w: 6, h: 25 },
    { t: "box", x: 38, w: 4, h: 19 },
    { t: "spire", x: 43, w: 6, h: 27, s: 5 },
    { t: "box", x: 50, w: 5, h: 21 },
    { t: "box", x: 56, w: 4, h: 16 },
    { t: "box", x: 61, w: 5, h: 24 },
    { t: "spire", x: 69, w: 8, h: 30, s: 8 },
    { t: "box", x: 78, w: 5, h: 18 },
    { t: "box", x: 84, w: 5, h: 13 },
    { t: "box", x: 90, w: 4, h: 15 },
    { t: "box", x: 95, w: 4, h: 9 },
  ],
  cameraBookmarks: [
    { id: "harlem", label: "Central Harlem", center: [-73.9465, 40.8116], zoom: 14, pitch: 60, bearing: 29 },
    { id: "mott", label: "Mott Haven", center: [-73.9235, 40.8089], zoom: 14, pitch: 58, bearing: -20 },
    { id: "fordham", label: "Fordham", center: [-73.8985, 40.8615], zoom: 13.6, pitch: 55, bearing: 10 },
    { id: "overview", label: "Harlem and the South Bronx", center: [-73.915, 40.833], zoom: 12.1, pitch: 48, bearing: 25 },
  ],
  attribution: [{ label: "© OpenStreetMap contributors", url: "https://www.openstreetmap.org/copyright" }],
  plannedSources: ["NYC Open Data (cooling centers, heat vulnerability index)", "NOAA heat", "U.S. Census ACS"],
};
