import type { CityPack } from "@/types";

export const miami: CityPack = {
  id: "miami",
  name: "Miami",
  state: "Florida",
  center: [-80.1918, 25.7617],
  initialZoom: 11.9,
  initialPitch: 56,
  initialBearing: 20,
  scenarioIds: ["miami-storm-surge-siege"],
  status: "playable",
  accent: "#22d3ee",
  accent2: "#2dd4bf",
  hazard: "Storm surge + compound flooding",
  scenarioTitle: "Storm Surge Siege",
  difficulty: 4,
  specialMechanic: "Compound Flooding",
  question: "Can you stay ahead of rising water?",
  populationTheme: "Low-elevation blocks far from the coast",
  hoverEffect: "surge",
  interventionCatalog: [],
  interventionNames: [
    "Evacuation Shelter",
    "Evacuation Bus Hub",
    "Temporary Flood Barrier",
    "Mobile Pump",
    "Protect Critical Road",
    "Emergency Medical Site",
    "Raised Supply Depot",
    "Deployable Coastal Barrier",
  ],
  skyline: [
    { t: "box", x: 2, w: 5, h: 10 },
    { t: "palm", x: 9, h: 12 },
    { t: "box", x: 13, w: 5, h: 22 },
    { t: "box", x: 19, w: 4, h: 28 },
    { t: "tower", x: 24, w: 6, h: 34 },
    { t: "box", x: 31, w: 5, h: 26 },
    { t: "box", x: 37, w: 6, h: 31 },
    { t: "spire", x: 44, w: 6, h: 33, s: 5 },
    { t: "box", x: 51, w: 5, h: 24 },
    { t: "box", x: 57, w: 4, h: 29 },
    { t: "box", x: 62, w: 6, h: 20 },
    { t: "palm", x: 70, h: 14 },
    { t: "box", x: 74, w: 5, h: 16 },
    { t: "box", x: 80, w: 6, h: 12 },
    { t: "palm", x: 89, h: 11 },
    { t: "box", x: 93, w: 5, h: 7 },
  ],
  cameraBookmarks: [
    { id: "brickell", label: "Brickell waterfront", center: [-80.1903, 25.7617], zoom: 14.2, pitch: 60, bearing: 20 },
    { id: "grove", label: "Coconut Grove", center: [-80.2397, 25.7275], zoom: 13.8, pitch: 55, bearing: -25 },
    { id: "river", label: "Miami River", center: [-80.2235, 25.7802], zoom: 13.6, pitch: 55, bearing: 40 },
    { id: "overview", label: "City overview", center: [-80.225, 25.78], zoom: 11.9, pitch: 45, bearing: 10 },
  ],
  attribution: [{ label: "© OpenStreetMap contributors", url: "https://www.openstreetmap.org/copyright" }],
  plannedSources: ["Miami-Dade Open Data", "NOAA storm surge (SLOSH)", "FEMA NFHL", "U.S. Census ACS"],
};
