import type { CityPack } from "@/types";

export const sanFrancisco: CityPack = {
  id: "san-francisco",
  name: "San Francisco",
  state: "California",
  center: [-122.4194, 37.7749],
  initialZoom: 12.1,
  initialPitch: 58,
  initialBearing: -28,
  scenarioIds: ["sf-the-big-one"],
  status: "playable",
  accent: "#fbbf24",
  accent2: "#f97316",
  hazard: "Earthquake + liquefaction + fire",
  scenarioTitle: "The Big One",
  difficulty: 5,
  specialMechanic: "Cascading Infrastructure Failure",
  question: "What fails after the shaking stops?",
  populationTheme: "Soft-story housing on liquefaction-prone fill",
  hoverEffect: "seismic",
  interventionCatalog: [],
  interventionNames: [
    "Seismic Retrofit",
    "Fire Response Staging",
    "Emergency Water Cache",
    "Medical Field Station",
    "Clear Emergency Corridor",
    "Temporary Shelter",
    "Search-and-Rescue Team",
    "Backup Communications Node",
  ],
  skyline: [
    { t: "box", x: 2, w: 6, h: 9 },
    { t: "tower", x: 9, w: 3, h: 26 },
    { t: "box", x: 14, w: 5, h: 14 },
    { t: "box", x: 20, w: 6, h: 20 },
    { t: "pyramid", x: 27, w: 9, h: 32 },
    { t: "box", x: 37, w: 5, h: 22 },
    { t: "box", x: 43, w: 7, h: 30 },
    { t: "box", x: 51, w: 5, h: 18 },
    { t: "box", x: 57, w: 6, h: 13 },
    { t: "tower", x: 66, w: 3, h: 24 },
    { t: "tower", x: 86, w: 3, h: 24 },
    { t: "box", x: 92, w: 6, h: 6 },
  ],
  cameraBookmarks: [
    { id: "marina", label: "Marina (filled land)", center: [-122.4368, 37.8037], zoom: 14.2, pitch: 58, bearing: 10 },
    { id: "soma", label: "SoMa and Mission Bay", center: [-122.3999, 37.7745], zoom: 14, pitch: 60, bearing: -28 },
    { id: "mission", label: "The Mission", center: [-122.4167, 37.7599], zoom: 14, pitch: 55, bearing: 15 },
    { id: "overview", label: "City overview", center: [-122.44, 37.765], zoom: 12.1, pitch: 45, bearing: -20 },
  ],
  attribution: [{ label: "© OpenStreetMap contributors", url: "https://www.openstreetmap.org/copyright" }],
  plannedSources: ["DataSF", "USGS ShakeMap scenarios", "California Geological Survey liquefaction zones", "U.S. Census ACS"],
};
