import type { StyleSpecification } from "maplibre-gl";

const FONT = ["Noto Sans Regular"];
const FONT_BOLD = ["Noto Sans Bold"];

/** Dark command-centre basemap on OpenFreeMap (OpenMapTiles schema, OpenStreetMap data). */
export function buildMapStyle(): StyleSpecification {
  return {
    version: 8,
    name: "faultline-command",
    projection: { type: "globe" },
    glyphs: "https://tiles.openfreemap.org/fonts/{fontstack}/{range}.pbf",
    sky: {
      "sky-color": "#06101f",
      "horizon-color": "#12304f",
      "fog-color": "#050a14",
      "fog-ground-blend": 0.6,
      "horizon-fog-blend": 0.4,
      "sky-horizon-blend": 0.7,
      "atmosphere-blend": ["interpolate", ["linear"], ["zoom"], 0, 1, 5, 1, 7, 0],
    },
    light: { anchor: "viewport", color: "#cfe3ff", intensity: 0.32, position: [1.2, 210, 35] },
    sources: {
      omt: { type: "vector", url: "https://tiles.openfreemap.org/planet" },
    },
    layers: [
      { id: "background", type: "background", paint: { "background-color": "#0c1424" } },
      {
        id: "landcover-wood",
        type: "fill",
        source: "omt",
        "source-layer": "landcover",
        filter: ["in", ["get", "class"], ["literal", ["wood", "forest"]]],
        paint: { "fill-color": "#0b1a1c", "fill-opacity": 0.85 },
      },
      {
        id: "landcover-grass",
        type: "fill",
        source: "omt",
        "source-layer": "landcover",
        filter: ["in", ["get", "class"], ["literal", ["grass", "wetland", "farmland"]]],
        paint: { "fill-color": "#0a1619", "fill-opacity": 0.8 },
      },
      {
        id: "park",
        type: "fill",
        source: "omt",
        "source-layer": "park",
        paint: { "fill-color": "#0c1d1e", "fill-opacity": 0.8 },
      },
      {
        id: "landuse-residential",
        type: "fill",
        source: "omt",
        "source-layer": "landuse",
        filter: ["==", ["get", "class"], "residential"],
        paint: { "fill-color": "#0e172a", "fill-opacity": 0.7 },
      },
      {
        id: "water",
        type: "fill",
        source: "omt",
        "source-layer": "water",
        paint: { "fill-color": "#040d1b" },
      },
      {
        id: "waterway",
        type: "line",
        source: "omt",
        "source-layer": "waterway",
        paint: {
          "line-color": "#1d5f8f",
          "line-width": ["interpolate", ["linear"], ["zoom"], 8, 0.4, 13, 1.4, 16, 3],
          "line-opacity": 0.9,
        },
      },
      {
        id: "boundary-country",
        type: "line",
        source: "omt",
        "source-layer": "boundary",
        filter: ["all", ["==", ["get", "admin_level"], 2], ["!=", ["get", "maritime"], 1]],
        paint: { "line-color": "#3b5a80", "line-width": 0.8, "line-opacity": 0.7 },
      },
      {
        id: "boundary-state",
        type: "line",
        source: "omt",
        "source-layer": "boundary",
        filter: ["all", ["==", ["get", "admin_level"], 4], ["!=", ["get", "maritime"], 1]],
        paint: { "line-color": "#2a4466", "line-width": 0.6, "line-dasharray": [2, 2], "line-opacity": 0.6 },
      },
      {
        id: "road-minor",
        type: "line",
        source: "omt",
        "source-layer": "transportation",
        minzoom: 12,
        filter: ["in", ["get", "class"], ["literal", ["minor", "service"]]],
        paint: {
          "line-color": "#16213a",
          "line-width": ["interpolate", ["linear"], ["zoom"], 12, 0.4, 16, 3],
        },
      },
      {
        id: "road-secondary",
        type: "line",
        source: "omt",
        "source-layer": "transportation",
        minzoom: 9,
        filter: ["in", ["get", "class"], ["literal", ["secondary", "tertiary"]]],
        paint: {
          "line-color": "#22314f",
          "line-width": ["interpolate", ["linear"], ["zoom"], 9, 0.5, 16, 5],
        },
      },
      {
        id: "road-primary",
        type: "line",
        source: "omt",
        "source-layer": "transportation",
        minzoom: 6,
        filter: ["in", ["get", "class"], ["literal", ["primary", "trunk"]]],
        paint: {
          "line-color": "#2c4166",
          "line-width": ["interpolate", ["linear"], ["zoom"], 6, 0.5, 16, 7],
        },
      },
      {
        id: "road-motorway",
        type: "line",
        source: "omt",
        "source-layer": "transportation",
        minzoom: 5,
        filter: ["==", ["get", "class"], "motorway"],
        paint: {
          "line-color": "#36507c",
          "line-width": ["interpolate", ["linear"], ["zoom"], 5, 0.6, 16, 9],
        },
      },
      {
        id: "rail",
        type: "line",
        source: "omt",
        "source-layer": "transportation",
        minzoom: 11,
        filter: ["==", ["get", "class"], "rail"],
        paint: { "line-color": "#1f2b44", "line-width": 1, "line-dasharray": [3, 3] },
      },
      {
        id: "building-3d",
        type: "fill-extrusion",
        source: "omt",
        "source-layer": "building",
        minzoom: 12.5,
        paint: {
          "fill-extrusion-color": [
            "interpolate",
            ["linear"],
            ["coalesce", ["get", "render_height"], 6],
            0,
            "#121b30",
            40,
            "#1b2a48",
            120,
            "#26406a",
          ],
          "fill-extrusion-height": ["interpolate", ["linear"], ["zoom"], 12.5, 0, 14, ["coalesce", ["get", "render_height"], 6]],
          "fill-extrusion-base": ["coalesce", ["get", "render_min_height"], 0],
          "fill-extrusion-opacity": 0.86,
          "fill-extrusion-vertical-gradient": true,
        },
      },
      {
        id: "road-label",
        type: "symbol",
        source: "omt",
        "source-layer": "transportation_name",
        minzoom: 13,
        filter: ["in", ["get", "class"], ["literal", ["primary", "secondary", "trunk", "motorway", "tertiary"]]],
        layout: {
          "symbol-placement": "line",
          "text-field": ["coalesce", ["get", "name:en"], ["get", "name"]],
          "text-font": FONT,
          "text-size": 10.5,
          "text-letter-spacing": 0.04,
        },
        paint: { "text-color": "#7f90ad", "text-halo-color": "#070c18", "text-halo-width": 1.4 },
      },
      {
        id: "water-label",
        type: "symbol",
        source: "omt",
        "source-layer": "waterway",
        minzoom: 12,
        filter: ["has", "name"],
        layout: {
          "symbol-placement": "line",
          "text-field": ["get", "name"],
          "text-font": ["Noto Sans Italic"],
          "text-size": 11,
          "text-letter-spacing": 0.05,
        },
        paint: { "text-color": "#4fa3d9", "text-halo-color": "#070c18", "text-halo-width": 1.2 },
      },
      {
        id: "place-neighbourhood",
        type: "symbol",
        source: "omt",
        "source-layer": "place",
        minzoom: 12,
        filter: ["in", ["get", "class"], ["literal", ["suburb", "neighbourhood", "quarter"]]],
        layout: {
          "text-field": ["coalesce", ["get", "name:en"], ["get", "name"]],
          "text-font": FONT,
          "text-size": 11,
          "text-transform": "uppercase",
          "text-letter-spacing": 0.15,
        },
        paint: { "text-color": "#5d6f8e", "text-halo-color": "#070c18", "text-halo-width": 1.2 },
      },
      {
        id: "place-city",
        type: "symbol",
        source: "omt",
        "source-layer": "place",
        minzoom: 4,
        maxzoom: 12,
        filter: ["in", ["get", "class"], ["literal", ["city"]]],
        layout: {
          "text-field": ["coalesce", ["get", "name:en"], ["get", "name"]],
          "text-font": FONT_BOLD,
          "text-size": ["interpolate", ["linear"], ["zoom"], 4, 10, 10, 15],
          "text-letter-spacing": 0.1,
        },
        paint: { "text-color": "#8ea2c3", "text-halo-color": "#070c18", "text-halo-width": 1.4 },
      },
      {
        id: "place-state",
        type: "symbol",
        source: "omt",
        "source-layer": "place",
        minzoom: 3,
        maxzoom: 7,
        filter: ["==", ["get", "class"], "state"],
        layout: {
          "text-field": ["coalesce", ["get", "name:en"], ["get", "name"]],
          "text-font": FONT,
          "text-size": 10,
          "text-transform": "uppercase",
          "text-letter-spacing": 0.25,
        },
        paint: { "text-color": "#3e5476", "text-halo-color": "#070c18", "text-halo-width": 1 },
      },
      {
        id: "place-country",
        type: "symbol",
        source: "omt",
        "source-layer": "place",
        maxzoom: 5,
        filter: ["==", ["get", "class"], "country"],
        layout: {
          "text-field": ["coalesce", ["get", "name:en"], ["get", "name"]],
          "text-font": FONT_BOLD,
          "text-size": 11,
          "text-transform": "uppercase",
          "text-letter-spacing": 0.3,
        },
        paint: { "text-color": "#4a6386", "text-halo-color": "#070c18", "text-halo-width": 1 },
      },
    ],
  };
}
